import { getLibPath } from "./utils.ts";

export default Deno.dlopen(
  getLibPath("yogacore"),
  {
    YGConfigGetInstanceCount: { parameters: [], result: "i32" },
    YGNodeNew: { parameters: [], result: "pointer" },
    YGNodeNewWithConfig: { parameters: ["pointer"], result: "pointer" },
    YGNodeFree: { parameters: ["pointer"], result: "void" },
    YGNodeReset: { parameters: ["pointer"], result: "void" },

    YGNodeSetContext: { parameters: ["pointer", "pointer"], result: "void" },
    YGNodeGetContext: { parameters: ["pointer"], result: "pointer" },

    YGConfigNew: { parameters: [], result: "pointer" },
    YGConfigFree: { parameters: ["pointer"], result: "void" },
    YGConfigSetExperimentalFeatureEnabled: { parameters: ["pointer", "i32", "i32"], result: "void" },
    YGConfigSetPointScaleFactor: { parameters: ["pointer", "f32"], result: "void" },
    YGConfigIsExperimentalFeatureEnabled: { parameters: ["pointer", "i32"], result: "i32" },

    YGNodeCopyStyle: { parameters: ["pointer", "pointer"], result: "void" },
    YGNodeStyleSetPositionType: { parameters: ["pointer", "i32"], result: "void" },
    YGNodeStyleSetPosition: { parameters: ["pointer", "i32", "f32"], result: "void" },
    YGNodeStyleSetPositionPercent: { parameters: ["pointer", "i32", "f32"], result: "void" },
    YGNodeStyleSetAlignContent: { parameters: ["pointer", "i32"], result: "void" },
    YGNodeStyleSetAlignItems: { parameters: ["pointer", "i32"], result: "void" },
    YGNodeStyleSetAlignSelf: { parameters: ["pointer", "i32"], result: "void" },
    YGNodeStyleSetFlexDirection: { parameters: ["pointer", "i32"], result: "void" },
    YGNodeStyleSetFlexWrap: { parameters: ["pointer", "i32"], result: "void" },
    YGNodeStyleSetJustifyContent: { parameters: ["pointer", "i32"], result: "void" },
    YGNodeStyleSetMargin: { parameters: ["pointer", "i32", "f32"], result: "void" },
    YGNodeStyleSetMarginPercent: { parameters: ["pointer", "i32", "f32"], result: "void" },
    YGNodeStyleSetMarginAuto: { parameters: ["pointer", "i32"], result: "void" },
    YGNodeStyleSetOverflow: { parameters: ["pointer", "i32"], result: "void" },
    YGNodeStyleSetDisplay: { parameters: ["pointer", "i32"], result: "void" },
    YGNodeStyleSetFlex: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetFlexBasis: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetFlexBasisPercent: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetFlexGrow: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetFlexShrink: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetWidth: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetWidthPercent: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetWidthAuto: { parameters: ["pointer"], result: "void" },
    YGNodeStyleSetHeight: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetHeightPercent: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetHeightAuto: { parameters: ["pointer"], result: "void" },
    YGNodeStyleSetMinWidth: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetMinWidthPercent: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetMinHeight: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetMinHeightPercent: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetMaxWidth: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetMaxWidthPercent: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetMaxHeight: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetMaxHeightPercent: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetAspectRatio: { parameters: ["pointer", "f32"], result: "void" },
    YGNodeStyleSetBorder: { parameters: ["pointer", "i32", "f32"], result: "void" },
    YGNodeStyleSetPadding: { parameters: ["pointer", "i32", "f32"], result: "void" },
    YGNodeStyleSetPaddingPercent: { parameters: ["pointer", "i32", "f32"], result: "void" },
    YGNodeSetIsReferenceBaseline: { parameters: ["pointer", "i32"], result: "void" },

    YGNodeStyleGetPositionType: { parameters: ["pointer"], result: "i32" },
    YGNodeStyleGetPosition: { parameters: ["pointer", "i32"], result: "i64" },
    YGNodeStyleGetAlignContent: { parameters: ["pointer"], result: "i32" },
    YGNodeStyleGetAlignItems: { parameters: ["pointer"], result: "i32" },
    YGNodeStyleGetAlignSelf: { parameters: ["pointer"], result: "i32" },
    YGNodeStyleGetFlexDirection: { parameters: ["pointer"], result: "i32" },
    YGNodeStyleGetFlexWrap: { parameters: ["pointer"], result: "i32" },
    YGNodeStyleGetJustifyContent: { parameters: ["pointer"], result: "i32" },
    YGNodeStyleGetMargin: { parameters: ["pointer", "i32"], result: "i64" },
    YGNodeStyleGetOverflow: { parameters: ["pointer"], result: "i32" },
    YGNodeStyleGetDisplay: { parameters: ["pointer"], result: "i32" },
    YGNodeStyleGetFlexBasis: { parameters: ["pointer"], result: "i64" },
    YGNodeStyleGetFlexGrow: { parameters: ["pointer"], result: "f32" },
    YGNodeStyleGetFlexShrink: { parameters: ["pointer"], result: "f32" },
    YGNodeStyleGetWidth: { parameters: ["pointer"], result: "i64" },
    YGNodeStyleGetHeight: { parameters: ["pointer"], result: "i64" },
    YGNodeStyleGetMinWidth: { parameters: ["pointer"], result: "i64" },
    YGNodeStyleGetMinHeight: { parameters: ["pointer"], result: "i64" },
    YGNodeStyleGetMaxWidth: { parameters: ["pointer"], result: "i64" },
    YGNodeStyleGetMaxHeight: { parameters: ["pointer"], result: "i64" },
    YGNodeStyleGetAspectRatio: { parameters: ["pointer"], result: "f32" },
    YGNodeStyleGetBorder: { parameters: ["pointer", "i32"], result: "f32" },
    YGNodeStyleGetPadding: { parameters: ["pointer", "i32"], result: "i64" },
    YGNodeIsReferenceBaseline: { parameters: ["pointer"], result: "i32" },

    YGNodeInsertChild: { parameters: ["pointer", "pointer", "usize"], result: "void" },
    YGNodeRemoveChild: { parameters: ["pointer", "pointer"], result: "void" },
    YGNodeGetChildCount: { parameters: ["pointer"], result: "usize" },
    YGNodeGetParent: { parameters: ["pointer"], result: "pointer" },
    YGNodeGetChild: { parameters: ["pointer", "usize"], result: "pointer" },

    YGNodeSetMeasureFunc: { parameters: ["pointer", "pointer"], result: "void" },
    YGNodeSetDirtiedFunc: { parameters: ["pointer", "pointer"], result: "void" },

    YGNodeMarkDirty: { parameters: ["pointer"], result: "void" },
    YGNodeIsDirty: { parameters: ["pointer"], result: "i32" },

    YGNodeCalculateLayout: { parameters: ["pointer", "f32", "f32", "i32"], result: "void" },
    YGNodeCalculateLayoutWithMagicNAN: { parameters: ["pointer", "f32", "f32", "i32"], result: "void" },
    YGNodeLayoutGetLeft: { parameters: ["pointer"], result: "f32" },
    YGNodeLayoutGetRight: { parameters: ["pointer"], result: "f32" },
    YGNodeLayoutGetTop: { parameters: ["pointer"], result: "f32" },
    YGNodeLayoutGetBottom: { parameters: ["pointer"], result: "f32" },
    YGNodeLayoutGetWidth: { parameters: ["pointer"], result: "f32" },
    YGNodeLayoutGetHeight: { parameters: ["pointer"], result: "f32" },
    YGNodeLayoutGetMargin: { parameters: ["pointer", "i32"], result: "f32" },
    YGNodeLayoutGetBorder: { parameters: ["pointer", "i32"], result: "f32" },
    YGNodeLayoutGetPadding: { parameters: ["pointer", "i32"], result: "f32" },
  } as const,
);
